FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Generate Prisma client
COPY prisma ./prisma/
RUN npm run prisma:generate

# Copy the rest of the application
COPY . .

# Prepare entrypoint
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["npm", "run", "start:dev"]
